### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by droter** [juancamilog/canbus_interface#2]
Hi,

I am getting this error when launching the package:
core service [/rosout] found
process[can/listener-1]: started with pid [20476]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/python_can-1.4-py2.7.egg/can/notifier.py", line 35, in rx_thread
    callback(msg)
  File "/usr/local/lib/python2.7/dist-packages/python_can-1.4-py2.7.egg/can/CAN.py", line 42, in __call**
    return self.on_message_received(msg)
  File "/home/matt/catkin_ws/src/canbus_interface/src/canbus_listener.py", line 23, in on_message_received
    self.canpub.publish(canframe)
AttributeError: 'canbus_ros_interface' object has no attribute 'canpub'

/home/matt/catkin_ws/src/canbus_interface/src/canbus_listener.py:13: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.canpub = rospy.Publisher('data', CanFrame)

Matt

**Comment by juancamilog** [comment]
Hi Matt,

I haven't touched this code on while. Sorry for the extremely late response. I will try to get some work on this in the next few days

**Comment by hashim19** [comment]
Hi Matt, 
Have you tried this with USB to CAN adapter ?
